// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateScene(arg1, arg2) {
  return window['go']['main']['App']['CreateScene'](arg1, arg2);
}

export function CreateShot(arg1) {
  return window['go']['main']['App']['CreateShot'](arg1);
}

export function ExtractLastFrame(arg1) {
  return window['go']['main']['App']['ExtractLastFrame'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetScenes(arg1) {
  return window['go']['main']['App']['GetScenes'](arg1);
}

export function GetShots(arg1, arg2) {
  return window['go']['main']['App']['GetShots'](arg1, arg2);
}

export function ReadImageBase64(arg1) {
  return window['go']['main']['App']['ReadImageBase64'](arg1);
}

export function SaveShots(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveShots'](arg1, arg2, arg3);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
