// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWorkflowExists() {
  return window['go']['main']['App']['CheckWorkflowExists']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateScene(arg1, arg2) {
  return window['go']['main']['App']['CreateScene'](arg1, arg2);
}

export function CreateShot(arg1) {
  return window['go']['main']['App']['CreateShot'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteScene(arg1, arg2) {
  return window['go']['main']['App']['DeleteScene'](arg1, arg2);
}

export function DeleteShot(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteShot'](arg1, arg2, arg3);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function ExtractLastFrame(arg1) {
  return window['go']['main']['App']['ExtractLastFrame'](arg1);
}

export function GetComfyURL() {
  return window['go']['main']['App']['GetComfyURL']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetScenes(arg1) {
  return window['go']['main']['App']['GetScenes'](arg1);
}

export function GetShots(arg1, arg2) {
  return window['go']['main']['App']['GetShots'](arg1, arg2);
}

export function GetTimeline(arg1, arg2) {
  return window['go']['main']['App']['GetTimeline'](arg1, arg2);
}

export function GetWorkflows() {
  return window['go']['main']['App']['GetWorkflows']();
}

export function ImportWorkflow(arg1) {
  return window['go']['main']['App']['ImportWorkflow'](arg1);
}

export function ReadImageBase64(arg1) {
  return window['go']['main']['App']['ReadImageBase64'](arg1);
}

export function RenameWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkflow'](arg1, arg2);
}

export function RenderShot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenderShot'](arg1, arg2, arg3, arg4);
}

export function SaveShots(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveShots'](arg1, arg2, arg3);
}

export function SaveTimeline(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTimeline'](arg1, arg2, arg3);
}

export function SelectAndSaveWorkflow() {
  return window['go']['main']['App']['SelectAndSaveWorkflow']();
}

export function SelectAudio() {
  return window['go']['main']['App']['SelectAudio']();
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SetComfyURL(arg1) {
  return window['go']['main']['App']['SetComfyURL'](arg1);
}

export function SetProjectThumbnail(arg1, arg2) {
  return window['go']['main']['App']['SetProjectThumbnail'](arg1, arg2);
}

export function TestComfyConnection() {
  return window['go']['main']['App']['TestComfyConnection']();
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTimeline(arg1) {
  return window['go']['main']['App']['UpdateTimeline'](arg1);
}
