// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:string,arg2:string):Promise<main.Project>;

export function CreateScene(arg1:string,arg2:string):Promise<main.Scene>;

export function CreateShot(arg1:string):Promise<main.Shot>;

export function ExtractLastFrame(arg1:string):Promise<string>;

export function GetProject(arg1:string):Promise<main.Project>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetScenes(arg1:string):Promise<Array<main.Scene>>;

export function GetShots(arg1:string,arg2:string):Promise<Array<main.Shot>>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function SaveShots(arg1:string,arg2:string,arg3:Array<main.Shot>):Promise<void>;

export function SelectImage():Promise<string>;

export function UpdateProject(arg1:main.Project):Promise<void>;
