// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckWorkflowExists():Promise<boolean>;

export function CreateProject(arg1:string,arg2:string):Promise<main.Project>;

export function CreateScene(arg1:string,arg2:string):Promise<main.Scene>;

export function CreateShot(arg1:string):Promise<main.Shot>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteScene(arg1:string,arg2:string):Promise<void>;

export function DeleteShot(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<string>;

export function ExtractLastFrame(arg1:string):Promise<string>;

export function GetComfyURL():Promise<string>;

export function GetProject(arg1:string):Promise<main.Project>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetScenes(arg1:string):Promise<Array<main.Scene>>;

export function GetShots(arg1:string,arg2:string):Promise<Array<main.Shot>>;

export function GetTimeline(arg1:string,arg2:string):Promise<main.TimelineData>;

export function GetWorkflows():Promise<Array<main.Workflow>>;

export function ImportWorkflow(arg1:string):Promise<string>;

export function Ping():Promise<boolean>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function RenameWorkflow(arg1:string,arg2:string):Promise<string>;

export function RenderShot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Shot>;

export function SaveShots(arg1:string,arg2:string,arg3:Array<main.Shot>):Promise<void>;

export function SaveTimeline(arg1:string,arg2:string,arg3:main.TimelineData):Promise<void>;

export function SelectAndSaveWorkflow():Promise<string>;

export function SelectAudio():Promise<string>;

export function SelectImage():Promise<string>;

export function SetComfyURL(arg1:string):Promise<void>;

export function SetProjectThumbnail(arg1:string,arg2:string):Promise<void>;

export function TestComfyConnection():Promise<boolean>;

export function UpdateProject(arg1:main.Project):Promise<void>;

export function UpdateTimeline(arg1:Array<string>):Promise<string>;
